@startuml
participant apps order 10
participant MessageQueue order 20
participant QueueProcessor order 30
participant TelegramSender order 40


apps -> MessageQueue: message1
apps -> MessageQueue: message2
apps -> MessageQueue: messageN
QueueProcessor --> MessageQueue: every 10 seconds
MessageQueue <-

apps -> MessageQueue: messageN+1

@enduml